// ******************************************************************************
//  © 2016 Sebastiaan Dammann - damsteen.nl
// 
//  File:           : Test.cs
//  Project         : NUnitTestOrdering.Tests
// ******************************************************************************

// <autogenerated>
// This file is generated by TestDataIndex.tt. Any changes will be lost
// when the file is regenerated. Do not edit this file.
// </autogenerated>

namespace NUnitTestOrdering.Tests.IntegrationTests {
    using NUnit.Framework;
    using System.Diagnostics.CodeAnalysis;
    using NUnitTestOrdering.Tests.TestData;
    using Support;

    [TestFixture]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public sealed class MethodOrdering {
        [Test]
        public void Simple() {
            // Given
            var input = TestDataDirectories.MethodOrdering.Simple();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

    }

    [TestFixture]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public sealed class PlainFixtureOrdering {
        [Test]
        public void HierarchySetupTeardown() {
            // Given
            var input = TestDataDirectories.PlainFixtureOrdering.HierarchySetupTeardown();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void NestedDeepHierarchy() {
            // Given
            var input = TestDataDirectories.PlainFixtureOrdering.NestedDeepHierarchy();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void OneDeepHierarchy() {
            // Given
            var input = TestDataDirectories.PlainFixtureOrdering.OneDeepHierarchy();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

    }

    [TestFixture]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public sealed class TestIntegrity {
        [Test]
        public void OrderedWithOrderAttribute() {
            // Given
            var input = TestDataDirectories.TestIntegrity.OrderedWithOrderAttribute();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void Single() {
            // Given
            var input = TestDataDirectories.TestIntegrity.Single();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void Single_WithActionAttribute() {
            // Given
            var input = TestDataDirectories.TestIntegrity.Single_WithActionAttribute();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void Single_WithSetupFixture() {
            // Given
            var input = TestDataDirectories.TestIntegrity.Single_WithSetupFixture();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

        [Test]
        public void Single_WithSetupTeardown() {
            // Given
            var input = TestDataDirectories.TestIntegrity.Single_WithSetupTeardown();
            string expectedResult = input.ReadResultsFile();

            // When
            string result;
            using (TestRunner testRunner = new TestRunner(input)) {
                result = testRunner.Run();
            }

            // Then
            Assert.That(result, Is.EqualTo(expectedResult));
        }

    }

}

namespace NUnitTestOrdering.Tests.TestData {
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.IO;
    using System.Reflection;
    using System.Text;

    public class TestDataDirectory {
       public string [] Files { get; set; }
       public string ExpectedResultFile { get;set; }

       public string ReadResultsFile() {
           Assembly thisAssembly = this.GetType().Assembly;
           StringBuilder resultsFile = new StringBuilder();

           Stream stream = thisAssembly.GetManifestResourceStream(this.ExpectedResultFile);
           if (stream == null) {
               throw new InvalidOperationException("Unknown manifest resource stream " + this.ExpectedResultFile);
           }

           using (StreamReader sr = new StreamReader(stream)) {
               string line;
               while ((line = sr.ReadLine()) != null) {
                   if (line.Length == 0 || line[0] == '#') {
                       // Skip "comment" line
                       continue;
                   }

                   resultsFile.AppendLine(line);
               }
           }

           resultsFile.Remove(resultsFile.Length - Environment.NewLine.Length, Environment.NewLine.Length);
           return resultsFile.ToString();
       }
    }

    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public static class TestDataDirectories {
		private static readonly string ThisAssemblyName = typeof(TestDataDirectory).Assembly.GetName().Name;

        public static class MethodOrdering {
            public static TestDataDirectory Simple() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.MethodOrdering.Simple.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.MethodOrdering.Simple.ExpectedTestResult.txt"
                };
            }
        }

        public static class PlainFixtureOrdering {
            public static TestDataDirectory HierarchySetupTeardown() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.HierarchySetupTeardown.AssemblyInfo.cs",
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.HierarchySetupTeardown.RootOrderedTestFixture.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.PlainFixtureOrdering.HierarchySetupTeardown.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory NestedDeepHierarchy() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.NestedDeepHierarchy.AssemblyInfo.cs",
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.NestedDeepHierarchy.DeepOrderedTestFixtureFirst.cs",
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.NestedDeepHierarchy.DeepOrderedTestFixtureFirst_Child.cs",
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.NestedDeepHierarchy.RootOrderedTestFixture.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.PlainFixtureOrdering.NestedDeepHierarchy.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory OneDeepHierarchy() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.OneDeepHierarchy.AssemblyInfo.cs",
                             ThisAssemblyName + "." + "TestData.PlainFixtureOrdering.OneDeepHierarchy.RootOrderedTestFixture.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.PlainFixtureOrdering.OneDeepHierarchy.ExpectedTestResult.txt"
                };
            }
        }

        public static class TestIntegrity {
            public static TestDataDirectory OrderedWithOrderAttribute() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.TestIntegrity.OrderedWithOrderAttribute.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.TestIntegrity.OrderedWithOrderAttribute.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory Single() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.TestIntegrity.Single.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory Single_WithActionAttribute() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithActionAttribute.AssemblyInfo.cs",
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithActionAttribute.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.TestIntegrity.Single_WithActionAttribute.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory Single_WithSetupFixture() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithSetupFixture.GlobalSetUpFixture.cs",
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithSetupFixture.NamespaceSetUpFixture.cs",
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithSetupFixture.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.TestIntegrity.Single_WithSetupFixture.ExpectedTestResult.txt"
                };
            }
            public static TestDataDirectory Single_WithSetupTeardown() {
                return new TestDataDirectory {
                    Files = new [] {
                             ThisAssemblyName + "." + "TestData.TestIntegrity.Single_WithSetupTeardown.Test.cs",
                             ThisAssemblyName + "." + @"TestData.Common.cs"
                        },

                    ExpectedResultFile = ThisAssemblyName + ".TestData.TestIntegrity.Single_WithSetupTeardown.ExpectedTestResult.txt"
                };
            }
        }

   }
}